kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: train-schedule
  name: train-schedule
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    k8s-app: train-schedule
  ports:
  - name: web
    port: 8083
    targetPort: 8080
    nodePort: 32222

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
  namespace: monitoring
  labels:
    k8s-app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: train-schedule
  template:
    metadata:
      labels:
        k8s-app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: jonsmall333/train-schedule:latest
        ports:
        - containerPort: 8080
      nodeSelector:
        node-type: worker

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: train-schedule
  namespace: monitoring
  labels:
    k8s-app: train-schedule-monitor
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      k8s-app: train-schedule
